name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
