name: Check Format
on: [push]
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
      - name: Install dependencies
        run: npm i
      - name: Check format
        run: npm run format-check
